"""empty message

Revision ID: 10c579398d90
Revises: 2e0a6134df42
Create Date: 2026-01-27 01:26:59.914614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10c579398d90'
down_revision: Union[str, Sequence[str], None] = '2e0a6134df42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('expected_amount', sa.Numeric(), nullable=False))
    op.drop_column('bills', 'amount_expression')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('amount_expression', sa.VARCHAR(length=1024), nullable=False))
    op.drop_column('bills', 'expected_amount')
    # ### end Alembic commands ###
