"""empty message

Revision ID: 2e0a6134df42
Revises: 
Create Date: 2026-01-27 01:17:18.823822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e0a6134df42'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('spent', sa.Numeric(), nullable=False))
    op.add_column('bills', sa.Column('name', sa.String(length=256), nullable=False))
    op.add_column('bills', sa.Column('regex_str', sa.String(length=256), nullable=False))
    op.add_column('bills', sa.Column('amount_expression', sa.String(length=1024), nullable=False))
    op.create_index(op.f('ix_bills_name'), 'bills', ['name'], unique=False)
    op.drop_column('bills', 'budget')
    op.drop_column('bills', 'category')
    op.create_index(op.f('ix_transactions_category'), 'transactions', ['category'], unique=False)
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category'), table_name='transactions')
    op.add_column('bills', sa.Column('category', sa.VARCHAR(length=256), nullable=False))
    op.add_column('bills', sa.Column('budget', sa.NUMERIC(), nullable=False))
    op.drop_index(op.f('ix_bills_name'), table_name='bills')
    op.drop_column('bills', 'amount_expression')
    op.drop_column('bills', 'regex_str')
    op.drop_column('bills', 'name')
    op.drop_column('bills', 'spent')
    # ### end Alembic commands ###
