"""empty message

Revision ID: 4b2f0bab9765
Revises: 10c579398d90
Create Date: 2026-01-28 15:31:58.921446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b2f0bab9765'
down_revision: Union[str, Sequence[str], None] = '10c579398d90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_bill_id', 'bills', ['bill_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bill_id', type_='foreignkey')

    # ### end Alembic commands ###
