"""empty message

Revision ID: 98ed601a6de0
Revises: 4b2f0bab9765
Create Date: 2026-01-28 16:46:40.953641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98ed601a6de0'
down_revision: Union[str, Sequence[str], None] = '4b2f0bab9765'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_column('spent')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.VARCHAR(length=512), nullable=False))

    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spent', sa.NUMERIC(), nullable=False))

    # ### end Alembic commands ###
