"""empty message

Revision ID: e96a94f73ccd
Revises: 2913935b7e8b
Create Date: 2026-01-30 13:15:22.408595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e96a94f73ccd'
down_revision: Union[str, Sequence[str], None] = '2913935b7e8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_charged', sa.DateTime(), nullable=True))
        batch_op.drop_column('last_updated')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.DATETIME(), nullable=True))
        batch_op.drop_column('last_charged')

    # ### end Alembic commands ###
